version: '3'

services:
  db:
    image: postgres:12
    restart: always
    container_name: db
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - TZ
    restart: unless-stopped
    ports:
      - 15432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/initdb.d:/docker-entrypoint-initdb.d

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile_${DOCKER_ENV}
    depends_on:
      - db
    ports:
      - 8080:8080
    restart: unless-stopped
    environment:
      - PORT
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - DB_HOST
      - DB_PORT
    volumes:
      - ./server:/usr/src/server
      - /usr/src/server/node_modules

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile_${DOCKER_ENV}
    depends_on:
      - db
      - server
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client:/usr/src/client
      - /usr/src/client/.next
      - /usr/src/client/node_modules

volumes:
  database:
    driver: local
