version: "3"
services:
  db:
    image: postgres:12
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: protein_review
    ports:
      - "15432:5432"
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
      - ./docker/db/initdb.d:/docker-entrypoint-initdb.d

volumes:
  database:
    driver: local